# Name of workflow
name: "Deploy App Image on AWS OCR"

# Run each push to dev branch
on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"

# Define envs
env:
  AWS_REGION: "eu-north-1"
  ECR_REPOSITORY: "140023404084.dkr.ecr.eu-north-1.amazonaws.com/python-test"
  EKS_CLUSTER_NAME: "dev-AKS-cluster"

# Define the job to create an image and push on ECR
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: AWS login
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: ECR login
        id: login-ecr
        uses: "aws-actions/amazon-ecr-login@v1"
      - name: Build Docker Image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }}:${{ github.sha }} .
      - name: Push Image to ERC
        run: |
          docker push ${{ env.ECR_REPOSITORY }}:${{ github.sha }}
      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
      - name: Deploy to EKS
        run: |
          sed -i.bak "s|DOCKER_IMAGE|${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}|g" deployment-dev.yaml && \
          kubectl apply -f kubernetes/dev/deployment.yaml
